
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (audio.EAudioType)_buf.ReadInt();
        ResourcePath = _buf.ReadString();
        Volume = _buf.ReadFloat();
        Loop = _buf.ReadBool();
        Cooldown = _buf.ReadFloat();
        Interruptible = _buf.ReadBool();
        FadeInOut = (audio.EAudioFade)_buf.ReadInt();
        AudioGroup = (audio.EAudioGroup)_buf.ReadInt();
    }

    public static Audio DeserializeAudio(ByteBuf _buf)
    {
        return new Audio(_buf);
    }

    /// <summary>
    /// 音频唯一id(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 粗分类(BGM/全局UI/局内玩法)
    /// </summary>
    public readonly audio.EAudioType Type;
    /// <summary>
    /// AudioClip资源路径
    /// </summary>
    public readonly string ResourcePath;
    /// <summary>
    /// 基础音量(0~1)
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 是否循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 专属防连点秒(0=用全局DefaultCooldown)
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 是否可被同通道高权重音效打断
    /// </summary>
    public readonly bool Interruptible;
    /// <summary>
    /// 淡入淡出模式
    /// </summary>
    public readonly audio.EAudioFade FadeInOut;
    /// <summary>
    /// 混音分组(Type的子类型)
    /// </summary>
    public readonly audio.EAudioGroup AudioGroup;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Type:" + Type + ","
        + "ResourcePath:" + ResourcePath + ","
        + "Volume:" + Volume + ","
        + "Loop:" + Loop + ","
        + "Cooldown:" + Cooldown + ","
        + "Interruptible:" + Interruptible + ","
        + "FadeInOut:" + FadeInOut + ","
        + "AudioGroup:" + AudioGroup + ","
        + "}";
    }
}

}
