
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.audio
{ 
    public enum EAudioFade
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 仅淡入
        /// </summary>
        In = 1,
        /// <summary>
        /// 仅淡出
        /// </summary>
        Out = 2,
        /// <summary>
        /// 双向
        /// </summary>
        Both = 3,
    }

} 

