
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.audio
{ 
    public enum EAudioType
    {
        /// <summary>
        /// 背景音乐
        /// </summary>
        BGM = 0,
        /// <summary>
        /// 全局UI音效
        /// </summary>
        GlobalUI = 1,
        /// <summary>
        /// 局内玩法音效
        /// </summary>
        InGame = 2,
    }

} 

