
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.audio
{
/// <summary>
/// 音频资源配置表(数据驱动播放)
/// </summary>
public partial class TbAudio
{
    private readonly System.Collections.Generic.Dictionary<int, Audio> _dataMap;
    private readonly System.Collections.Generic.List<Audio> _dataList;
    
    public TbAudio(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Audio>();
        _dataList = new System.Collections.Generic.List<Audio>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Audio _v;
            _v = Audio.DeserializeAudio(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Audio> DataMap => _dataMap;
    public System.Collections.Generic.List<Audio> DataList => _dataList;

    public Audio GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Audio Get(int key) => _dataMap[key];
    public Audio this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
