
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.audio
{ 
    public enum EAudioGroup
    {
        /// <summary>
        /// 全局
        /// </summary>
        Global = 0,
        /// <summary>
        /// 背景音乐
        /// </summary>
        BGM = 1,
        /// <summary>
        /// 界面
        /// </summary>
        UI = 2,
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 3,
        /// <summary>
        /// 语音
        /// </summary>
        Voice = 4,
    }

} 

