
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.avatar
{ 
    public enum EUnlockCond
    {
        /// <summary>
        /// 等级解锁
        /// </summary>
        LEVEL = 1,
        /// <summary>
        /// 活动发放
        /// </summary>
        EVENT = 2,
    }

} 

