
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.avatar
{ 
    public enum EAvatarType
    {
        /// <summary>
        /// 头像
        /// </summary>
        AVATAR = 1,
        /// <summary>
        /// 头像框
        /// </summary>
        FRAME = 2,
    }

} 

