
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.avatar
{
/// <summary>
/// 头像与头像框表
/// </summary>
public partial class TbAvatar
{
    private readonly System.Collections.Generic.Dictionary<int, Avatar> _dataMap;
    private readonly System.Collections.Generic.List<Avatar> _dataList;
    
    public TbAvatar(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Avatar>();
        _dataList = new System.Collections.Generic.List<Avatar>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Avatar _v;
            _v = Avatar.DeserializeAvatar(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Avatar> DataMap => _dataMap;
    public System.Collections.Generic.List<Avatar> DataList => _dataList;

    public Avatar GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Avatar Get(int key) => _dataMap[key];
    public Avatar this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
