
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Avatar : Luban.BeanBase
{
    public Avatar(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (avatar.EAvatarType)_buf.ReadInt();
        Image = _buf.ReadString();
        UnlockText = _buf.ReadInt();
        UnlockCond = (avatar.EUnlockCond)_buf.ReadInt();
        UnlockParam = _buf.ReadInt();
    }

    public static Avatar DeserializeAvatar(ByteBuf _buf)
    {
        return new Avatar(_buf);
    }

    /// <summary>
    /// 头像id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型(1头像2框)
    /// </summary>
    public readonly avatar.EAvatarType Type;
    /// <summary>
    /// 图片资源名
    /// </summary>
    public readonly string Image;
    /// <summary>
    /// 解锁文字id
    /// </summary>
    public readonly int UnlockText;
    /// <summary>
    /// 解锁条件(1等级2活动)
    /// </summary>
    public readonly avatar.EUnlockCond UnlockCond;
    /// <summary>
    /// 条件参数(等级/活动id)
    /// </summary>
    public readonly int UnlockParam;
   
    public const int __ID__ = 1972874617;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "image:" + Image + ","
        + "unlockText:" + UnlockText + ","
        + "unlockCond:" + UnlockCond + ","
        + "unlockParam:" + UnlockParam + ","
        + "}";
    }
}

}
