
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.block
{
/// <summary>
/// BlockBlast动态权重tier表
/// </summary>
public partial class TbWeightCfg
{
    private readonly System.Collections.Generic.Dictionary<int, WeightCfg> _dataMap;
    private readonly System.Collections.Generic.List<WeightCfg> _dataList;
    
    public TbWeightCfg(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeightCfg>();
        _dataList = new System.Collections.Generic.List<WeightCfg>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WeightCfg _v;
            _v = WeightCfg.DeserializeWeightCfg(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeightCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<WeightCfg> DataList => _dataList;

    public WeightCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeightCfg Get(int key) => _dataMap[key];
    public WeightCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
