
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.block
{
/// <summary>
/// 女神满档领取奖励表(行=等级+数量;元素类型运行时取当前未交付订单所需类型)
/// </summary>
public partial class TbGoddessReward
{
    private readonly System.Collections.Generic.Dictionary<int, GoddessReward> _dataMap;
    private readonly System.Collections.Generic.List<GoddessReward> _dataList;
    
    public TbGoddessReward(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GoddessReward>();
        _dataList = new System.Collections.Generic.List<GoddessReward>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GoddessReward _v;
            _v = GoddessReward.DeserializeGoddessReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GoddessReward> DataMap => _dataMap;
    public System.Collections.Generic.List<GoddessReward> DataList => _dataList;

    public GoddessReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GoddessReward Get(int key) => _dataMap[key];
    public GoddessReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
