
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.block
{
/// <summary>
/// 塔罗牌收集表(22张大阿卡纳;碎片凑齐手动合成)
/// </summary>
public partial class TbTarotCard
{
    private readonly System.Collections.Generic.Dictionary<int, TarotCard> _dataMap;
    private readonly System.Collections.Generic.List<TarotCard> _dataList;
    
    public TbTarotCard(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TarotCard>();
        _dataList = new System.Collections.Generic.List<TarotCard>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TarotCard _v;
            _v = TarotCard.DeserializeTarotCard(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TarotCard> DataMap => _dataMap;
    public System.Collections.Generic.List<TarotCard> DataList => _dataList;

    public TarotCard GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TarotCard Get(int key) => _dataMap[key];
    public TarotCard this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
