
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.block
{
/// <summary>
/// 订单池表(池序=id升序;奖励直配值;碎片=塔罗收集掉落源)
/// </summary>
public partial class TbMergeOrder
{
    private readonly System.Collections.Generic.Dictionary<int, MergeOrder> _dataMap;
    private readonly System.Collections.Generic.List<MergeOrder> _dataList;
    
    public TbMergeOrder(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MergeOrder>();
        _dataList = new System.Collections.Generic.List<MergeOrder>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MergeOrder _v;
            _v = MergeOrder.DeserializeMergeOrder(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MergeOrder> DataMap => _dataMap;
    public System.Collections.Generic.List<MergeOrder> DataList => _dataList;

    public MergeOrder GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MergeOrder Get(int key) => _dataMap[key];
    public MergeOrder this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
