
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GiftSelect : Luban.BeanBase
{
    public GiftSelect(ByteBuf _buf) 
    {
        AutoId = _buf.ReadInt();
        Index = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        Num = _buf.ReadInt();
        Rate = _buf.ReadInt();
    }

    public static GiftSelect DeserializeGiftSelect(ByteBuf _buf)
    {
        return new GiftSelect(_buf);
    }

    /// <summary>
    /// 行主键(index=auto_id)
    /// </summary>
    public readonly int AutoId;
    /// <summary>
    /// 所属礼包id(同index=一个奖池)
    /// </summary>
    public readonly int Index;
    /// <summary>
    /// 奖品道具id(指向item.TbItemDef)
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 该奖品数量
    /// </summary>
    public readonly int Num;
    /// <summary>
    /// 权重(抽中概率=rate/同index全部rate之和)
    /// </summary>
    public readonly int Rate;
   
    public const int __ID__ = 2145305196;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "autoId:" + AutoId + ","
        + "index:" + Index + ","
        + "itemId:" + ItemId + ","
        + "num:" + Num + ","
        + "rate:" + Rate + ","
        + "}";
    }
}

}
