
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GoddessReward : Luban.BeanBase
{
    public GoddessReward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static GoddessReward DeserializeGoddessReward(ByteBuf _buf)
    {
        return new GoddessReward(_buf);
    }

    /// <summary>
    /// 行主键(女神奖励档 当前单档)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 发放元素等级(1-5)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 发放数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -1867820404;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "count:" + Count + ","
        + "}";
    }
}

}
