
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 随机礼包池表
/// </summary>
public partial class TbGiftRandom
{
    private readonly System.Collections.Generic.Dictionary<int, GiftRandom> _dataMap;
    private readonly System.Collections.Generic.List<GiftRandom> _dataList;
    
    public TbGiftRandom(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GiftRandom>();
        _dataList = new System.Collections.Generic.List<GiftRandom>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GiftRandom _v;
            _v = GiftRandom.DeserializeGiftRandom(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AutoId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GiftRandom> DataMap => _dataMap;
    public System.Collections.Generic.List<GiftRandom> DataList => _dataList;

    public GiftRandom GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GiftRandom Get(int key) => _dataMap[key];
    public GiftRandom this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
