
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    public enum EItemQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        COMMON = 1,
        /// <summary>
        /// 高级
        /// </summary>
        FINE = 2,
        /// <summary>
        /// 精英
        /// </summary>
        ELITE = 3,
        /// <summary>
        /// 史诗
        /// </summary>
        EPIC = 4,
        /// <summary>
        /// 传说
        /// </summary>
        LEGEND = 5,
        /// <summary>
        /// 神话
        /// </summary>
        MYTH = 6,
    }

} 

