
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 道具定义表
/// </summary>
public partial class TbItemDef
{
    private readonly System.Collections.Generic.Dictionary<int, ItemDef> _dataMap;
    private readonly System.Collections.Generic.List<ItemDef> _dataList;
    
    public TbItemDef(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemDef>();
        _dataList = new System.Collections.Generic.List<ItemDef>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ItemDef _v;
            _v = ItemDef.DeserializeItemDef(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemDef> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemDef> DataList => _dataList;

    public ItemDef GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemDef Get(int key) => _dataMap[key];
    public ItemDef this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
