
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ItemDef : Luban.BeanBase
{
    public ItemDef(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        Desc = _buf.ReadInt();
        Icon = _buf.ReadString();
        Quality = (item.EItemQuality)_buf.ReadInt();
        Light = _buf.ReadString();
        Automatic = _buf.ReadInt();
        Type = (item.EItemType)_buf.ReadInt();
        Param = _buf.ReadInt();
        UseEffect = _buf.ReadInt();
        UseValue = _buf.ReadInt();
        UseNum = _buf.ReadInt();
        UseLevel = _buf.ReadInt();
        Stacking = _buf.ReadInt();
        Term = _buf.ReadInt();
        TermPrompt = _buf.ReadInt();
        TermTime = _buf.ReadString();
        Compensate = _buf.ReadInt();
        CompensateEmail = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);JumpList = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); JumpList[__index0] = __e0;}}
    }

    public static ItemDef DeserializeItemDef(ByteBuf _buf)
    {
        return new ItemDef(_buf);
    }

    /// <summary>
    /// 道具唯一id(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名(多语言文本id)
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// 道具描述(多语言文本id)
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 品质(1-6)
    /// </summary>
    public readonly item.EItemQuality Quality;
    /// <summary>
    /// icon特效id/路径
    /// </summary>
    public readonly string Light;
    /// <summary>
    /// 获得时是否自动使用(0否1是)
    /// </summary>
    public readonly int Automatic;
    /// <summary>
    /// 道具类型(分类/背包归类)
    /// </summary>
    public readonly item.EItemType Type;
    /// <summary>
    /// 参数:自选/随机礼包奖励数量/开启次数
    /// </summary>
    public readonly int Param;
    /// <summary>
    /// 使用效果:0无1num2图案3自选礼包id4随机礼包id
    /// </summary>
    public readonly int UseEffect;
    /// <summary>
    /// 使用效果目标id:1时num_id/2时图案key/3时自选index/4时随机index
    /// </summary>
    public readonly int UseValue;
    /// <summary>
    /// 使用效果数量:1货币数量/2图案数量
    /// </summary>
    public readonly int UseNum;
    /// <summary>
    /// 图案等级(2时1-3其余0)
    /// </summary>
    public readonly int UseLevel;
    /// <summary>
    /// 可叠放(0否1是;上限999)
    /// </summary>
    public readonly int Stacking;
    /// <summary>
    /// 限时(0非限时1指定日期2指定时长)
    /// </summary>
    public readonly int Term;
    /// <summary>
    /// 限时提示(文本id)
    /// </summary>
    public readonly int TermPrompt;
    /// <summary>
    /// 限时时间(日期串/时长秒)
    /// </summary>
    public readonly string TermTime;
    /// <summary>
    /// 到期补偿(Reward表id)
    /// </summary>
    public readonly int Compensate;
    /// <summary>
    /// 补偿邮件(邮件id)
    /// </summary>
    public readonly int CompensateEmail;
    /// <summary>
    /// 获取跳转列表
    /// </summary>
    public readonly int[] JumpList;
   
    public const int __ID__ = -514135086;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "quality:" + Quality + ","
        + "light:" + Light + ","
        + "automatic:" + Automatic + ","
        + "type:" + Type + ","
        + "param:" + Param + ","
        + "useEffect:" + UseEffect + ","
        + "useValue:" + UseValue + ","
        + "useNum:" + UseNum + ","
        + "useLevel:" + UseLevel + ","
        + "stacking:" + Stacking + ","
        + "term:" + Term + ","
        + "termPrompt:" + TermPrompt + ","
        + "termTime:" + TermTime + ","
        + "compensate:" + Compensate + ","
        + "compensateEmail:" + CompensateEmail + ","
        + "jumpList:" + Luban.StringUtil.CollectionToString(JumpList) + ","
        + "}";
    }
}

}
