
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 自选礼包池表
/// </summary>
public partial class TbGiftSelect
{
    private readonly System.Collections.Generic.Dictionary<int, GiftSelect> _dataMap;
    private readonly System.Collections.Generic.List<GiftSelect> _dataList;
    
    public TbGiftSelect(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GiftSelect>();
        _dataList = new System.Collections.Generic.List<GiftSelect>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GiftSelect _v;
            _v = GiftSelect.DeserializeGiftSelect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AutoId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GiftSelect> DataMap => _dataMap;
    public System.Collections.Generic.List<GiftSelect> DataList => _dataList;

    public GiftSelect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GiftSelect Get(int key) => _dataMap[key];
    public GiftSelect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
