
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    public enum EItemType
    {
        /// <summary>
        /// 货币
        /// </summary>
        CURRENCY = 1,
        /// <summary>
        /// 材料
        /// </summary>
        MATERIAL = 2,
        /// <summary>
        /// 功能材料
        /// </summary>
        FUNC_MATERIAL = 3,
        /// <summary>
        /// 自选礼包
        /// </summary>
        GIFT_SELECT = 5,
        /// <summary>
        /// 随机礼包
        /// </summary>
        GIFT_RANDOM = 6,
    }

} 

