
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MailGlobal : Luban.BeanBase
{
    public MailGlobal(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
        RetainDays = _buf.ReadInt();
    }

    public static MailGlobal DeserializeMailGlobal(ByteBuf _buf)
    {
        return new MailGlobal(_buf);
    }

    /// <summary>
    /// 配置id(主键,固定1)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 收件箱总上限N(超量删最早)
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 默认保留天数(保留期默认一月)
    /// </summary>
    public readonly int RetainDays;
   
    public const int __ID__ = 332360794;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "maxCount:" + MaxCount + ","
        + "retainDays:" + RetainDays + ","
        + "}";
    }
}

}
