
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.mail
{
/// <summary>
/// 邮件全局配置表(单行)
/// </summary>
public partial class TbMailGlobal
{
    private readonly System.Collections.Generic.Dictionary<int, MailGlobal> _dataMap;
    private readonly System.Collections.Generic.List<MailGlobal> _dataList;
    
    public TbMailGlobal(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MailGlobal>();
        _dataList = new System.Collections.Generic.List<MailGlobal>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MailGlobal _v;
            _v = MailGlobal.DeserializeMailGlobal(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MailGlobal> DataMap => _dataMap;
    public System.Collections.Generic.List<MailGlobal> DataList => _dataList;

    public MailGlobal GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MailGlobal Get(int key) => _dataMap[key];
    public MailGlobal this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
