
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Mail : Luban.BeanBase
{
    public Mail(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Title = _buf.ReadInt();
        Desc = _buf.ReadInt();
        ExpireDays = _buf.ReadInt();
        RewardId = _buf.ReadInt();
    }

    public static Mail DeserializeMail(ByteBuf _buf)
    {
        return new Mail(_buf);
    }

    /// <summary>
    /// 邮件模板id(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题(多语言textId)
    /// </summary>
    public readonly int Title;
    /// <summary>
    /// 内容(多语言textId)
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 有效期(天);0/负用全局retainDays
    /// </summary>
    public readonly int ExpireDays;
    /// <summary>
    /// 奖励随机库表id(0=无奖励;指向gift_random index)
    /// </summary>
    public readonly int RewardId;
   
    public const int __ID__ = 2390487;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "desc:" + Desc + ","
        + "expireDays:" + ExpireDays + ","
        + "rewardId:" + RewardId + ","
        + "}";
    }
}

}
