
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.mail
{
/// <summary>
/// 通用邮件模板表
/// </summary>
public partial class TbMail
{
    private readonly System.Collections.Generic.Dictionary<int, Mail> _dataMap;
    private readonly System.Collections.Generic.List<Mail> _dataList;
    
    public TbMail(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Mail>();
        _dataList = new System.Collections.Generic.List<Mail>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Mail _v;
            _v = Mail.DeserializeMail(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Mail> DataMap => _dataMap;
    public System.Collections.Generic.List<Mail> DataList => _dataList;

    public Mail GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Mail Get(int key) => _dataMap[key];
    public Mail this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
