
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MergeOrder : Luban.BeanBase
{
    public MergeOrder(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ElementType = _buf.ReadInt();
        Level = _buf.ReadInt();
        Count = _buf.ReadInt();
        EnergyReward = _buf.ReadInt();
        PietyReward = _buf.ReadInt();
        FragmentItemId = _buf.ReadInt();
        FragmentCount = _buf.ReadInt();
    }

    public static MergeOrder DeserializeMergeOrder(ByteBuf _buf)
    {
        return new MergeOrder(_buf);
    }

    /// <summary>
    /// 订单池行号(池序=id升序;游标按池长取模)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 元素类型(=客户端MergeElement;1蝶2杯3卷4星)
    /// </summary>
    public readonly int ElementType;
    /// <summary>
    /// 元素等级(1-5)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 需求数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 交付奖励体力
    /// </summary>
    public readonly int EnergyReward;
    /// <summary>
    /// 交付奖励虔诚币
    /// </summary>
    public readonly int PietyReward;
    /// <summary>
    /// 掉落塔罗碎片道具id(=TbItemDef行)
    /// </summary>
    public readonly int FragmentItemId;
    /// <summary>
    /// 掉落碎片数量
    /// </summary>
    public readonly int FragmentCount;
   
    public const int __ID__ = 887534102;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "elementType:" + ElementType + ","
        + "level:" + Level + ","
        + "count:" + Count + ","
        + "energyReward:" + EnergyReward + ","
        + "pietyReward:" + PietyReward + ","
        + "fragmentItemId:" + FragmentItemId + ","
        + "fragmentCount:" + FragmentCount + ","
        + "}";
    }
}

}
