
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.num
{ 
    public enum ENumType
    {
        /// <summary>
        /// 经验
        /// </summary>
        EXP = 1,
        /// <summary>
        /// 虔诚币
        /// </summary>
        PIETY = 2,
        /// <summary>
        /// 钻石
        /// </summary>
        DIAMOND = 3,
        /// <summary>
        /// 体力
        /// </summary>
        ENERGY = 4,
    }

} 

