
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.num
{
/// <summary>
/// 数值底层货币表
/// </summary>
public partial class TbNum
{
    private readonly System.Collections.Generic.Dictionary<int, Num> _dataMap;
    private readonly System.Collections.Generic.List<Num> _dataList;
    
    public TbNum(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Num>();
        _dataList = new System.Collections.Generic.List<Num>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Num _v;
            _v = Num.DeserializeNum(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Num> DataMap => _dataMap;
    public System.Collections.Generic.List<Num> DataList => _dataList;

    public Num GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Num Get(int key) => _dataMap[key];
    public Num this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
