
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Num : Luban.BeanBase
{
    public Num(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadInt();
        Name = _buf.ReadInt();
        Icon = _buf.ReadString();
        NumType = (num.ENumType)_buf.ReadInt();
        Quality = _buf.ReadInt();
    }

    public static Num DeserializeNum(ByteBuf _buf)
    {
        return new Num(_buf);
    }

    /// <summary>
    /// 资源id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述文本id
    /// </summary>
    public readonly int Desc;
    /// <summary>
    /// 名称文本id
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly num.ENumType NumType;
    /// <summary>
    /// 数值品质
    /// </summary>
    public readonly int Quality;
   
    public const int __ID__ = 78694;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "numType:" + NumType + ","
        + "quality:" + Quality + ","
        + "}";
    }
}

}
