
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.rank
{
/// <summary>
/// rank board table (multi-tier per id)
/// </summary>
public partial class TbRank
{
    private readonly System.Collections.Generic.Dictionary<int, Rank> _dataMap;
    private readonly System.Collections.Generic.List<Rank> _dataList;
    
    public TbRank(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Rank>();
        _dataList = new System.Collections.Generic.List<Rank>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Rank _v;
            _v = Rank.DeserializeRank(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Rank> DataMap => _dataMap;
    public System.Collections.Generic.List<Rank> DataList => _dataList;

    public Rank GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Rank Get(int key) => _dataMap[key];
    public Rank this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
