
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Rank : Luban.BeanBase
{
    public Rank(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        Id = _buf.ReadInt();
        Name = _buf.ReadInt();
        RankGroup = _buf.ReadInt();
        RankMethod = _buf.ReadInt();
        RankCondition = _buf.ReadLong();
        RankMin = _buf.ReadInt();
        RankMax = _buf.ReadInt();
        Reward = _buf.ReadInt();
        RankShowReward = _buf.ReadInt();
        RewardPraise = _buf.ReadInt();
        RewardDaily = _buf.ReadInt();
        ValidType = _buf.ReadInt();
        ValidVal = _buf.ReadLong();
        Mail = _buf.ReadInt();
        RankCountMax = _buf.ReadInt();
        ShowCountMax = _buf.ReadInt();
    }

    public static Rank DeserializeRank(ByteBuf _buf)
    {
        return new Rank(_buf);
    }

    /// <summary>
    /// row primary key
    /// </summary>
    public readonly int RowId;
    /// <summary>
    /// rank id (repeatable=multi tier)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// name textId
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// rank group
    /// </summary>
    public readonly int RankGroup;
    /// <summary>
    /// play method
    /// </summary>
    public readonly int RankMethod;
    /// <summary>
    /// enter condition
    /// </summary>
    public readonly long RankCondition;
    /// <summary>
    /// rank min(incl)
    /// </summary>
    public readonly int RankMin;
    /// <summary>
    /// rank max(incl)
    /// </summary>
    public readonly int RankMax;
    /// <summary>
    /// reward pool id(0=none)
    /// </summary>
    public readonly int Reward;
    /// <summary>
    /// show reward pool(0=same)
    /// </summary>
    public readonly int RankShowReward;
    /// <summary>
    /// praise pool(0=none)
    /// </summary>
    public readonly int RewardPraise;
    /// <summary>
    /// daily pool(0=none)
    /// </summary>
    public readonly int RewardDaily;
    /// <summary>
    /// valid type 0/1/2/3
    /// </summary>
    public readonly int ValidType;
    /// <summary>
    /// valid val
    /// </summary>
    public readonly long ValidVal;
    /// <summary>
    /// settle mail def id
    /// </summary>
    public readonly int Mail;
    /// <summary>
    /// count max
    /// </summary>
    public readonly int RankCountMax;
    /// <summary>
    /// show max
    /// </summary>
    public readonly int ShowCountMax;
   
    public const int __ID__ = 2539596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "rowId:" + RowId + ","
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rankGroup:" + RankGroup + ","
        + "rankMethod:" + RankMethod + ","
        + "rankCondition:" + RankCondition + ","
        + "rankMin:" + RankMin + ","
        + "rankMax:" + RankMax + ","
        + "reward:" + Reward + ","
        + "rankShowReward:" + RankShowReward + ","
        + "rewardPraise:" + RewardPraise + ","
        + "rewardDaily:" + RewardDaily + ","
        + "validType:" + ValidType + ","
        + "validVal:" + ValidVal + ","
        + "mail:" + Mail + ","
        + "rankCountMax:" + RankCountMax + ","
        + "showCountMax:" + ShowCountMax + ","
        + "}";
    }
}

}
