
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.redeem
{
/// <summary>
/// 通用兑换码主表
/// </summary>
public partial class TbRedeemCode
{
    private readonly System.Collections.Generic.Dictionary<string, RedeemCode> _dataMap;
    private readonly System.Collections.Generic.List<RedeemCode> _dataList;
    
    public TbRedeemCode(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RedeemCode>();
        _dataList = new System.Collections.Generic.List<RedeemCode>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RedeemCode _v;
            _v = RedeemCode.DeserializeRedeemCode(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RedeemCode> DataMap => _dataMap;
    public System.Collections.Generic.List<RedeemCode> DataList => _dataList;

    public RedeemCode GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RedeemCode Get(string key) => _dataMap[key];
    public RedeemCode this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
