
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RedeemCode : Luban.BeanBase
{
    public RedeemCode(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        Name = _buf.ReadInt();
        OncePerPlayer = _buf.ReadInt();
        ExpireTime = _buf.ReadString();
    }

    public static RedeemCode DeserializeRedeemCode(ByteBuf _buf)
    {
        return new RedeemCode(_buf);
    }

    /// <summary>
    /// 兑换码字符串(主键,规整后大写存)
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 码名称/用途(文本id)
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// 每玩家仅一次:1是0否,默认1
    /// </summary>
    public readonly int OncePerPlayer;
    /// <summary>
    /// 过期时间(日期串,空=不限时)
    /// </summary>
    public readonly string ExpireTime;
   
    public const int __ID__ = -473265719;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "oncePerPlayer:" + OncePerPlayer + ","
        + "expireTime:" + ExpireTime + ","
        + "}";
    }
}

}
