
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.redeem
{
/// <summary>
/// 兑换码奖励子表(按code聚合)
/// </summary>
public partial class TbRedeemReward
{
    private readonly System.Collections.Generic.Dictionary<int, RedeemReward> _dataMap;
    private readonly System.Collections.Generic.List<RedeemReward> _dataList;
    
    public TbRedeemReward(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RedeemReward>();
        _dataList = new System.Collections.Generic.List<RedeemReward>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RedeemReward _v;
            _v = RedeemReward.DeserializeRedeemReward(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AutoId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RedeemReward> DataMap => _dataMap;
    public System.Collections.Generic.List<RedeemReward> DataList => _dataList;

    public RedeemReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RedeemReward Get(int key) => _dataMap[key];
    public RedeemReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
