
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RedeemReward : Luban.BeanBase
{
    public RedeemReward(ByteBuf _buf) 
    {
        AutoId = _buf.ReadInt();
        Code = _buf.ReadString();
        ItemId = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static RedeemReward DeserializeRedeemReward(ByteBuf _buf)
    {
        return new RedeemReward(_buf);
    }

    /// <summary>
    /// 自增id(主键)
    /// </summary>
    public readonly int AutoId;
    /// <summary>
    /// 所属兑换码(外键-&gt;redeemcode.code)
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 奖励道具id(指向item.TbItemDef)
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = 878945291;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "autoId:" + AutoId + ","
        + "code:" + Code + ","
        + "itemId:" + ItemId + ","
        + "num:" + Num + ","
        + "}";
    }
}

}
