
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    /// <summary>
    /// BlockBlast动态权重tier表
    /// </summary>
    private block.TbWeightCfg m_TbWeightCfg;
    public block.TbWeightCfg TbWeightCfg 
    {
        get
        {
            if (m_TbWeightCfg == null)
            {
                m_TbWeightCfg = new block.TbWeightCfg(defaultLoader("block_tbweightcfg"));
                m_TbWeightCfg.ResolveRef(this);
            }
            return m_TbWeightCfg;
        }
        set
        {
            m_TbWeightCfg = value;
            m_TbWeightCfg.ResolveRef(this);
        }
    }
    /// <summary>
    /// 数值底层货币表
    /// </summary>
    private num.TbNum m_TbNum;
    public num.TbNum TbNum 
    {
        get
        {
            if (m_TbNum == null)
            {
                m_TbNum = new num.TbNum(defaultLoader("num_tbnum"));
                m_TbNum.ResolveRef(this);
            }
            return m_TbNum;
        }
        set
        {
            m_TbNum = value;
            m_TbNum.ResolveRef(this);
        }
    }
    /// <summary>
    /// 道具定义表
    /// </summary>
    private item.TbItemDef m_TbItemDef;
    public item.TbItemDef TbItemDef 
    {
        get
        {
            if (m_TbItemDef == null)
            {
                m_TbItemDef = new item.TbItemDef(defaultLoader("item_tbitemdef"));
                m_TbItemDef.ResolveRef(this);
            }
            return m_TbItemDef;
        }
        set
        {
            m_TbItemDef = value;
            m_TbItemDef.ResolveRef(this);
        }
    }
    /// <summary>
    /// 随机礼包池表
    /// </summary>
    private item.TbGiftRandom m_TbGiftRandom;
    public item.TbGiftRandom TbGiftRandom 
    {
        get
        {
            if (m_TbGiftRandom == null)
            {
                m_TbGiftRandom = new item.TbGiftRandom(defaultLoader("item_tbgiftrandom"));
                m_TbGiftRandom.ResolveRef(this);
            }
            return m_TbGiftRandom;
        }
        set
        {
            m_TbGiftRandom = value;
            m_TbGiftRandom.ResolveRef(this);
        }
    }
    /// <summary>
    /// 自选礼包池表
    /// </summary>
    private item.TbGiftSelect m_TbGiftSelect;
    public item.TbGiftSelect TbGiftSelect 
    {
        get
        {
            if (m_TbGiftSelect == null)
            {
                m_TbGiftSelect = new item.TbGiftSelect(defaultLoader("item_tbgiftselect"));
                m_TbGiftSelect.ResolveRef(this);
            }
            return m_TbGiftSelect;
        }
        set
        {
            m_TbGiftSelect = value;
            m_TbGiftSelect.ResolveRef(this);
        }
    }
    /// <summary>
    /// 头像与头像框表
    /// </summary>
    private avatar.TbAvatar m_TbAvatar;
    public avatar.TbAvatar TbAvatar 
    {
        get
        {
            if (m_TbAvatar == null)
            {
                m_TbAvatar = new avatar.TbAvatar(defaultLoader("avatar_tbavatar"));
                m_TbAvatar.ResolveRef(this);
            }
            return m_TbAvatar;
        }
        set
        {
            m_TbAvatar = value;
            m_TbAvatar.ResolveRef(this);
        }
    }
    /// <summary>
    /// 通用兑换码主表
    /// </summary>
    private redeem.TbRedeemCode m_TbRedeemCode;
    public redeem.TbRedeemCode TbRedeemCode 
    {
        get
        {
            if (m_TbRedeemCode == null)
            {
                m_TbRedeemCode = new redeem.TbRedeemCode(defaultLoader("redeem_tbredeemcode"));
                m_TbRedeemCode.ResolveRef(this);
            }
            return m_TbRedeemCode;
        }
        set
        {
            m_TbRedeemCode = value;
            m_TbRedeemCode.ResolveRef(this);
        }
    }
    /// <summary>
    /// 兑换码奖励子表(按code聚合)
    /// </summary>
    private redeem.TbRedeemReward m_TbRedeemReward;
    public redeem.TbRedeemReward TbRedeemReward 
    {
        get
        {
            if (m_TbRedeemReward == null)
            {
                m_TbRedeemReward = new redeem.TbRedeemReward(defaultLoader("redeem_tbredeemreward"));
                m_TbRedeemReward.ResolveRef(this);
            }
            return m_TbRedeemReward;
        }
        set
        {
            m_TbRedeemReward = value;
            m_TbRedeemReward.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
