
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// BlockBlast动态权重tier表
    /// </summary>
    private block.TbWeightCfg m_TbWeightCfg;
    public block.TbWeightCfg TbWeightCfg 
    {
        get
        {
            if (m_TbWeightCfg == null)
            {
                m_TbWeightCfg = new block.TbWeightCfg(defaultLoader("block_tbweightcfg"));
                m_TbWeightCfg.ResolveRef(this);
            }
            return m_TbWeightCfg;
        }
        set
        {
            m_TbWeightCfg = value;
            m_TbWeightCfg.ResolveRef(this);
        }
    }
    /// <summary>
    /// 数值底层货币表
    /// </summary>
    private num.TbNum m_TbNum;
    public num.TbNum TbNum 
    {
        get
        {
            if (m_TbNum == null)
            {
                m_TbNum = new num.TbNum(defaultLoader("num_tbnum"));
                m_TbNum.ResolveRef(this);
            }
            return m_TbNum;
        }
        set
        {
            m_TbNum = value;
            m_TbNum.ResolveRef(this);
        }
    }
    /// <summary>
    /// 道具定义表
    /// </summary>
    private item.TbItemDef m_TbItemDef;
    public item.TbItemDef TbItemDef 
    {
        get
        {
            if (m_TbItemDef == null)
            {
                m_TbItemDef = new item.TbItemDef(defaultLoader("item_tbitemdef"));
                m_TbItemDef.ResolveRef(this);
            }
            return m_TbItemDef;
        }
        set
        {
            m_TbItemDef = value;
            m_TbItemDef.ResolveRef(this);
        }
    }
    /// <summary>
    /// 随机礼包池表
    /// </summary>
    private item.TbGiftRandom m_TbGiftRandom;
    public item.TbGiftRandom TbGiftRandom 
    {
        get
        {
            if (m_TbGiftRandom == null)
            {
                m_TbGiftRandom = new item.TbGiftRandom(defaultLoader("item_tbgiftrandom"));
                m_TbGiftRandom.ResolveRef(this);
            }
            return m_TbGiftRandom;
        }
        set
        {
            m_TbGiftRandom = value;
            m_TbGiftRandom.ResolveRef(this);
        }
    }
    /// <summary>
    /// 自选礼包池表
    /// </summary>
    private item.TbGiftSelect m_TbGiftSelect;
    public item.TbGiftSelect TbGiftSelect 
    {
        get
        {
            if (m_TbGiftSelect == null)
            {
                m_TbGiftSelect = new item.TbGiftSelect(defaultLoader("item_tbgiftselect"));
                m_TbGiftSelect.ResolveRef(this);
            }
            return m_TbGiftSelect;
        }
        set
        {
            m_TbGiftSelect = value;
            m_TbGiftSelect.ResolveRef(this);
        }
    }
    /// <summary>
    /// 头像与头像框表
    /// </summary>
    private avatar.TbAvatar m_TbAvatar;
    public avatar.TbAvatar TbAvatar 
    {
        get
        {
            if (m_TbAvatar == null)
            {
                m_TbAvatar = new avatar.TbAvatar(defaultLoader("avatar_tbavatar"));
                m_TbAvatar.ResolveRef(this);
            }
            return m_TbAvatar;
        }
        set
        {
            m_TbAvatar = value;
            m_TbAvatar.ResolveRef(this);
        }
    }
    /// <summary>
    /// 通用邮件模板表
    /// </summary>
    private mail.TbMail m_TbMail;
    public mail.TbMail TbMail 
    {
        get
        {
            if (m_TbMail == null)
            {
                m_TbMail = new mail.TbMail(defaultLoader("mail_tbmail"));
                m_TbMail.ResolveRef(this);
            }
            return m_TbMail;
        }
        set
        {
            m_TbMail = value;
            m_TbMail.ResolveRef(this);
        }
    }
    /// <summary>
    /// 邮件全局配置表(单行)
    /// </summary>
    private mail.TbMailGlobal m_TbMailGlobal;
    public mail.TbMailGlobal TbMailGlobal 
    {
        get
        {
            if (m_TbMailGlobal == null)
            {
                m_TbMailGlobal = new mail.TbMailGlobal(defaultLoader("mail_tbmailglobal"));
                m_TbMailGlobal.ResolveRef(this);
            }
            return m_TbMailGlobal;
        }
        set
        {
            m_TbMailGlobal = value;
            m_TbMailGlobal.ResolveRef(this);
        }
    }
    /// <summary>
    /// rank board table (multi-tier per id)
    /// </summary>
    private rank.TbRank m_TbRank;
    public rank.TbRank TbRank 
    {
        get
        {
            if (m_TbRank == null)
            {
                m_TbRank = new rank.TbRank(defaultLoader("rank_tbrank"));
                m_TbRank.ResolveRef(this);
            }
            return m_TbRank;
        }
        set
        {
            m_TbRank = value;
            m_TbRank.ResolveRef(this);
        }
    }
    /// <summary>
    /// 全局零散参数配置表(键值型,value按需解析)
    /// </summary>
    private global.TbGlobal m_TbGlobal;
    public global.TbGlobal TbGlobal 
    {
        get
        {
            if (m_TbGlobal == null)
            {
                m_TbGlobal = new global.TbGlobal(defaultLoader("global_tbglobal"));
                m_TbGlobal.ResolveRef(this);
            }
            return m_TbGlobal;
        }
        set
        {
            m_TbGlobal = value;
            m_TbGlobal.ResolveRef(this);
        }
    }
    /// <summary>
    /// 订单池表(池序=id升序;奖励直配值;碎片=塔罗收集掉落源)
    /// </summary>
    private block.TbMergeOrder m_TbMergeOrder;
    public block.TbMergeOrder TbMergeOrder 
    {
        get
        {
            if (m_TbMergeOrder == null)
            {
                m_TbMergeOrder = new block.TbMergeOrder(defaultLoader("block_tbmergeorder"));
                m_TbMergeOrder.ResolveRef(this);
            }
            return m_TbMergeOrder;
        }
        set
        {
            m_TbMergeOrder = value;
            m_TbMergeOrder.ResolveRef(this);
        }
    }
    /// <summary>
    /// 塔罗牌收集表(22张大阿卡纳;碎片凑齐手动合成)
    /// </summary>
    private block.TbTarotCard m_TbTarotCard;
    public block.TbTarotCard TbTarotCard 
    {
        get
        {
            if (m_TbTarotCard == null)
            {
                m_TbTarotCard = new block.TbTarotCard(defaultLoader("block_tbtarotcard"));
                m_TbTarotCard.ResolveRef(this);
            }
            return m_TbTarotCard;
        }
        set
        {
            m_TbTarotCard = value;
            m_TbTarotCard.ResolveRef(this);
        }
    }
    /// <summary>
    /// 音频资源配置表(数据驱动播放)
    /// </summary>
    private audio.TbAudio m_TbAudio;
    public audio.TbAudio TbAudio 
    {
        get
        {
            if (m_TbAudio == null)
            {
                m_TbAudio = new audio.TbAudio(defaultLoader("audio_tbaudio"));
                m_TbAudio.ResolveRef(this);
            }
            return m_TbAudio;
        }
        set
        {
            m_TbAudio = value;
            m_TbAudio.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
