
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class TarotCard : Luban.BeanBase
{
    public TarotCard(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Icon = _buf.ReadString();
        FragmentItemId = _buf.ReadInt();
        FragmentsNeeded = _buf.ReadInt();
    }

    public static TarotCard DeserializeTarotCard(ByteBuf _buf)
    {
        return new TarotCard(_buf);
    }

    /// <summary>
    /// 塔罗牌id(1-22大阿卡纳序)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 牌名(图鉴显示)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 牌面图标资源名
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 对应碎片道具id(=TbItemDef行)
    /// </summary>
    public readonly int FragmentItemId;
    /// <summary>
    /// 合成所需碎片数
    /// </summary>
    public readonly int FragmentsNeeded;
   
    public const int __ID__ = 1429819994;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "fragmentItemId:" + FragmentItemId + ","
        + "fragmentsNeeded:" + FragmentsNeeded + ","
        + "}";
    }
}

}
