
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class WeightCfg : Luban.BeanBase
{
    public WeightCfg(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        FillBlankOdds = _buf.ReadInt();
        RandomOdds = _buf.ReadInt();
        EntropyOdds = _buf.ReadInt();
        EasyOdds = _buf.ReadInt();
        HardOdds = _buf.ReadInt();
        IntuitionOdds = _buf.ReadInt();
        Clearboard = _buf.ReadInt();
        Allunite = _buf.ReadInt();
        HighScoreMin = _buf.ReadInt();
        HighScoreMax = _buf.ReadInt();
        FactorLow = _buf.ReadInt();
        FactorHigh = _buf.ReadInt();
    }

    public static WeightCfg DeserializeWeightCfg(ByteBuf _buf)
    {
        return new WeightCfg(_buf);
    }

    /// <summary>
    /// 动态权重tier ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 填空消除算法权重
    /// </summary>
    public readonly int FillBlankOdds;
    /// <summary>
    /// 随机无死亡算法权重
    /// </summary>
    public readonly int RandomOdds;
    /// <summary>
    /// 熵增算法权重
    /// </summary>
    public readonly int EntropyOdds;
    /// <summary>
    /// 简单难题权重
    /// </summary>
    public readonly int EasyOdds;
    /// <summary>
    /// 困难难题权重
    /// </summary>
    public readonly int HardOdds;
    /// <summary>
    /// 直觉死亡难题权重
    /// </summary>
    public readonly int IntuitionOdds;
    /// <summary>
    /// 清盘Plus权重
    /// </summary>
    public readonly int Clearboard;
    /// <summary>
    /// 全组合填空消除权重
    /// </summary>
    public readonly int Allunite;
    /// <summary>
    /// 分数下限
    /// </summary>
    public readonly int HighScoreMin;
    /// <summary>
    /// 分数上限-1无上限
    /// </summary>
    public readonly int HighScoreMax;
    /// <summary>
    /// FactorRange0
    /// </summary>
    public readonly int FactorLow;
    /// <summary>
    /// FactorRange1
    /// </summary>
    public readonly int FactorHigh;
   
    public const int __ID__ = -952552788;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "FillBlankOdds:" + FillBlankOdds + ","
        + "RandomOdds:" + RandomOdds + ","
        + "EntropyOdds:" + EntropyOdds + ","
        + "EasyOdds:" + EasyOdds + ","
        + "HardOdds:" + HardOdds + ","
        + "IntuitionOdds:" + IntuitionOdds + ","
        + "Clearboard:" + Clearboard + ","
        + "Allunite:" + Allunite + ","
        + "HighScoreMin:" + HighScoreMin + ","
        + "HighScoreMax:" + HighScoreMax + ","
        + "FactorLow:" + FactorLow + ","
        + "FactorHigh:" + FactorHigh + ","
        + "}";
    }
}

}
