using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Analyzer;

[Generator]
public class EventInterfaceGenerator : ISourceGenerator
{
    private sealed class EventCenterInterfaceInfo
    {
        public string InterfaceName { get; set; } = string.Empty;
        public string EventClassName { get; set; } = string.Empty;
        public string GroupClassName { get; set; } = string.Empty;
        public List<EventCenterMethodInfo> Methods { get; } = new List<EventCenterMethodInfo>();
    }

    private sealed class EventCenterMethodInfo
    {
        public string MethodName { get; set; } = string.Empty;
        public string ActionType { get; set; } = string.Empty;
    }

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var syntaxTrees = context.Compilation.SyntaxTrees;
        List<string> classNameList = new List<string>();
        List<EventCenterInterfaceInfo> eventCenterInterfaceInfos = new List<EventCenterInterfaceInfo>();

        foreach (var tree in syntaxTrees)
        {
            var root = tree.GetRoot();
            var interfaces = root.DescendantNodes()
                .OfType<InterfaceDeclarationSyntax>()
                .Where(i => i.AttributeLists.Count > 0 &&
                            i.AttributeLists
                             .Any(a => a.Attributes
                             .Any(attr => attr.Name.ToString() == $"{Definition.EventInterface}")));

            foreach (var interfaceNode in interfaces)
            {
                var interfaceName = interfaceNode.Identifier.ToString();
                var fullName = interfaceNode.SyntaxTree.GetRoot()
                    .DescendantNodes()
                    .OfType<NamespaceDeclarationSyntax>()
                    .Select(ns => ns.Name.ToString())
                    .Concat(new[] { interfaceName })
                    .Aggregate((a, b) => a + "." + b);
                var eventClassName = $"{interfaceName}_Event";
                var eventClassCode = GenerateEventClass(interfaceName, eventClassName, interfaceNode);

                context.AddSource($"{eventClassName}.g.cs", eventClassCode);

                var implementationClassCode = GenerateImplementationClass(fullName, interfaceName, interfaceNode, context);
                context.AddSource($"{interfaceName}_Gen.g.cs", implementationClassCode);

                classNameList.Add($"{interfaceName}_Gen");
                eventCenterInterfaceInfos.Add(GenerateEventCenterInterfaceInfo(interfaceName, eventClassName, interfaceNode, context));
            }
        }

        if (classNameList.Count > 0)
        {
            string uniqueFileName = $"GameEventHelper.g.cs";
            context.AddSource(uniqueFileName, GenerateGameEventHelper(classNameList));
            context.AddSource("EventCenter.g.cs", GenerateEventCenter(eventCenterInterfaceInfos));
        }
    }

    private string GenerateGameEventHelper(List<string> classNameList)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine($"//  <auto-generated>");
        sb.AppendLine($"//     This code was generated by autoBindTool.");
        sb.AppendLine($"//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine($"//     the code is regenerated.");
        sb.AppendLine($"//  </auto-generated>");
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine($"using UnityEngine.UI;");
        sb.AppendLine($"using {Definition.FrameworkNameSpace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public static class GameEventHelper");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static void Init()");
        sb.AppendLine("        {");

        foreach (var className in classNameList)
        {
            sb.AppendLine($"            var m_{className} = new {className}(GameEvent.EventMgr.GetDispatcher());");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateEventCenter(List<EventCenterInterfaceInfo> eventCenterInterfaceInfos)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine($"//  <auto-generated>");
        sb.AppendLine($"//     This code was generated by autoBindTool.");
        sb.AppendLine($"//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine($"//     the code is regenerated.");
        sb.AppendLine($"//  </auto-generated>");
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine($"using UnityEngine.UI;");
        sb.AppendLine($"using {Definition.FrameworkNameSpace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public partial class EventCenter");
        sb.AppendLine("    {");
        GenerateEventCenterGroup(sb, eventCenterInterfaceInfos, "AddEvent", "AddEventListener");
        sb.AppendLine();
        GenerateEventCenterGroup(sb, eventCenterInterfaceInfos, "RemoveEvent", "RemoveEventListener");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private void GenerateEventCenterGroup(StringBuilder sb, List<EventCenterInterfaceInfo> eventCenterInterfaceInfos, string className, string methodName)
    {
        sb.AppendLine($"        public partial class {className}");
        sb.AppendLine("        {");

        for (int i = 0; i < eventCenterInterfaceInfos.Count; i++)
        {
            var interfaceInfo = eventCenterInterfaceInfos[i];
            sb.AppendLine($"            public partial class {interfaceInfo.GroupClassName}");
            sb.AppendLine("            {");

            for (int j = 0; j < interfaceInfo.Methods.Count; j++)
            {
                var eventMethod = interfaceInfo.Methods[j];
                sb.AppendLine($"                public static void {eventMethod.MethodName}({eventMethod.ActionType} action)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    GameEvent.{methodName}({interfaceInfo.EventClassName}.{eventMethod.MethodName}, action);");
                sb.AppendLine("                }");

                if (j < interfaceInfo.Methods.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("            }");

            if (i < eventCenterInterfaceInfos.Count - 1)
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("        }");
    }

    private EventCenterInterfaceInfo GenerateEventCenterInterfaceInfo(string interfaceName, string eventClassName, InterfaceDeclarationSyntax interfaceNode, GeneratorExecutionContext context)
    {
        var semanticModel = context.Compilation.GetSemanticModel(interfaceNode.SyntaxTree);
        var eventCenterInterfaceInfo = new EventCenterInterfaceInfo
        {
            InterfaceName = interfaceName,
            EventClassName = eventClassName,
            GroupClassName = GetEventCenterGroupName(interfaceName),
        };

        foreach (var method in interfaceNode.Members.OfType<MethodDeclarationSyntax>())
        {
            eventCenterInterfaceInfo.Methods.Add(new EventCenterMethodInfo
            {
                MethodName = method.Identifier.ToString(),
                ActionType = GenerateActionType(method, semanticModel),
            });
        }

        return eventCenterInterfaceInfo;
    }

    private string GetEventCenterGroupName(string interfaceName)
    {
        if (interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1]))
        {
            return interfaceName.Substring(1);
        }

        return interfaceName;
    }

    private string GenerateActionType(MethodDeclarationSyntax method, SemanticModel semanticModel)
    {
        var parameterTypes = method.ParameterList.Parameters
            .Select(parameter => GenerateParameterType(parameter, semanticModel))
            .ToList();

        if (parameterTypes.Count == 0)
        {
            return "System.Action";
        }

        return $"System.Action<{string.Join(", ", parameterTypes)}>";
    }

    private string GenerateParameterType(ParameterSyntax parameter, SemanticModel semanticModel)
    {
        if (parameter.Type == null)
        {
            return "object";
        }

        var typeSymbol = semanticModel.GetTypeInfo(parameter.Type).Type;
        return typeSymbol != null ? typeSymbol.ToDisplayString() : parameter.Type.ToString();
    }

    private string GenerateEventClass(string interfaceName, string className, InterfaceDeclarationSyntax interfaceNode)
    {
        var methods = interfaceNode.Members.OfType<MethodDeclarationSyntax>();
        var sb = new StringBuilder();

        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine($"//\t<auto-generated>");
        sb.AppendLine($"//\t\tThis code was generated by autoBindTool.");
        sb.AppendLine($"//\t\tChanges to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine($"//\t\tthe code is regenerated.");
        sb.AppendLine($"//\t</auto-generated>");
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine($"using UnityEngine.UI;");
        sb.AppendLine($"using {Definition.FrameworkNameSpace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        foreach (var method in methods)
        {
            var methodName = method.Identifier.ToString();
            var parameters = string.Join(", ", method.ParameterList.Parameters.Select(p => $"{p.Type} {p.Identifier}"));
            sb.AppendLine($"        public static readonly int {methodName} = {Definition.StringToHash}(\"{className}.{methodName}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateImplementationClass(string interfaceFullName, string interfaceName, InterfaceDeclarationSyntax interfaceNode, GeneratorExecutionContext context)
    {
        var semanticModel = context.Compilation.GetSemanticModel(interfaceNode.SyntaxTree);
        var sb = new StringBuilder();

        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine($"//\t<auto-generated>");
        sb.AppendLine($"//\t\tThis code was generated by autoBindTool.");
        sb.AppendLine($"//\t\tChanges to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine($"//\t\tthe code is regenerated.");
        sb.AppendLine($"//\t</auto-generated>");
        sb.AppendLine($"//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine($"using UnityEngine;");
        sb.AppendLine($"using UnityEngine.UI;");
        sb.AppendLine($"using {Definition.FrameworkNameSpace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {Definition.NameSpace}");
        sb.AppendLine($"{{");
        sb.AppendLine($"    public partial class {interfaceName}_Gen : {interfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private EventDispatcher _dispatcher;");
        sb.AppendLine($"        public {interfaceName}_Gen(EventDispatcher dispatcher)");
        sb.AppendLine("        {");
        sb.AppendLine("            _dispatcher = dispatcher;");
        sb.AppendLine($"             GameEvent.EventMgr.RegWrapInterface<{interfaceFullName}>(this);");
        sb.AppendLine("        }");

        foreach (var method in interfaceNode.Members.OfType<MethodDeclarationSyntax>())
        {
            var methodName = method.Identifier.ToString();
            var parameters = GenerateParameters(method, semanticModel);

            sb.AppendLine($"        public void {methodName}({parameters})");
            sb.AppendLine("        {");
            if (method.ParameterList.Parameters.Count > 0)
            {
                var paramNames = string.Join(", ", method.ParameterList.Parameters.Select(p => p.Identifier.ToString()));
                sb.AppendLine($"            _dispatcher.Send({interfaceName}_Event.{methodName}, {paramNames});");
            }
            else
            {
                sb.AppendLine($"            _dispatcher.Send({interfaceName}_Event.{methodName});");
            }
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateParameters(MethodDeclarationSyntax method, SemanticModel semanticModel)
    {
        return string.Join(", ", method.ParameterList.Parameters.Select(p =>
        {
            if (p.Type == null)
            {
                return $"object {p.Identifier}";
            }

            var typeSymbol = semanticModel.GetTypeInfo(p.Type).Type;
            return typeSymbol != null
                ? $"{typeSymbol.ToDisplayString()} {p.Identifier}"
                : $"{p.Type} {p.Identifier}";
        }));
    }
}